/* tslint:disable */
/* eslint-disable */
/**
 * Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CodeResponseDto {
    'code': number;
    'value': string;
    'order': number;
}
export interface CodeValueDto {
    'code'?: number;
    'value': string;
}

/**
 * ApiFinTechClient - axios parameter creator
 */
export const ApiFinTechClientAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Array<CodeValueDto>} codeValueDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCodes: async (codeValueDto: Array<CodeValueDto>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'codeValueDto' is not null or undefined
            assertParamExists('addCodes', 'codeValueDto', codeValueDto)
            const localVarPath = `/codes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(codeValueDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [search] 
         * @param {number} [skip] 
         * @param {number} [take] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCodes: async (search?: string, skip?: number, take?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/codes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['Search'] = search;
            }

            if (skip !== undefined) {
                localVarQueryParameter['Skip'] = skip;
            }

            if (take !== undefined) {
                localVarQueryParameter['Take'] = take;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getValuesByCode: async (code: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('getValuesByCode', 'code', code)
            const localVarPath = `/codes/{code}/value`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ApiFinTechClient - functional programming interface
 */
export const ApiFinTechClientFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ApiFinTechClientAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {Array<CodeValueDto>} codeValueDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addCodes(codeValueDto: Array<CodeValueDto>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CodeResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addCodes(codeValueDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiFinTechClient.addCodes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [search] 
         * @param {number} [skip] 
         * @param {number} [take] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCodes(search?: string, skip?: number, take?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CodeResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCodes(search, skip, take, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiFinTechClient.getCodes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getValuesByCode(code: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getValuesByCode(code, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ApiFinTechClient.getValuesByCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ApiFinTechClient - factory interface
 */
export const ApiFinTechClientFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ApiFinTechClientFp(configuration)
    return {
        /**
         * 
         * @param {Array<CodeValueDto>} codeValueDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCodes(codeValueDto: Array<CodeValueDto>, options?: RawAxiosRequestConfig): AxiosPromise<Array<CodeResponseDto>> {
            return localVarFp.addCodes(codeValueDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [search] 
         * @param {number} [skip] 
         * @param {number} [take] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCodes(search?: string, skip?: number, take?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<CodeResponseDto>> {
            return localVarFp.getCodes(search, skip, take, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} code 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getValuesByCode(code: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<string>> {
            return localVarFp.getValuesByCode(code, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ApiFinTechClient - object-oriented interface
 */
export class ApiFinTechClient extends BaseAPI {
    /**
     * 
     * @param {Array<CodeValueDto>} codeValueDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addCodes(codeValueDto: Array<CodeValueDto>, options?: RawAxiosRequestConfig) {
        return ApiFinTechClientFp(this.configuration).addCodes(codeValueDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [search] 
     * @param {number} [skip] 
     * @param {number} [take] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCodes(search?: string, skip?: number, take?: number, options?: RawAxiosRequestConfig) {
        return ApiFinTechClientFp(this.configuration).getCodes(search, skip, take, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} code 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getValuesByCode(code: number, options?: RawAxiosRequestConfig) {
        return ApiFinTechClientFp(this.configuration).getValuesByCode(code, options).then((request) => request(this.axios, this.basePath));
    }
}



